
        git config --global user.name "Radar-Bot"
        git config --global user.email "radar-bot@users.noreply.github.com"
        git add events.json
        if ! git diff --cached --quiet; then
          git commit -m "Autarkes Euro-Update von heute"
          git pull origin main --rebase --strategy-option=theirs
          git push origin main
        else
          echo "Keine Änderungen gefunden."
        fi
